feat: add button link component
traefik/faency pull request #219
Opened 2021-12-02 19:13 UTC by seedy

### Description

We have use cases for `Button`s which hold `href`

- Added a `LinkButton` component
- Added a story inside Button folder

### Accessibility concerns

Links and Buttons should not be mixed together

2021-12-09 09:45 UTC, seedy commented on components/Button/Button.tsx
> +export const StyledLinkButton = styled('a', buttonStyles);
@paulocfjunior I just noticed you have `state="active"` on the ButtonLink record.

`state="active"` impacts button behaviour.

I'm updating the `state` control to reset `state` to undefined

2021-12-10 14:01 UTC, matthieuh approved these changes
LGTM

2021-12-10 14:06 UTC, matthieuh reviewed
_deleted comment: somehow GH is approving PRs only adding a review comment 🤔_

2021-12-10 14:08 UTC, matthieuh reviewed
How is it different from using <Button as="a" ... syntax ?
In the future, I would suggest having proposals as RFC issues to avoid starting any implementation before we validate them as a team.

2021-12-10 14:09 UTC, matthieuh requested changes
How is it different from using <Button as="a" ... syntax?
In the future, I would suggest having proposals as RFC issues to avoid starting any implementation before we validate them as a team.

2021-12-10 14:52 UTC, seedy commented
> How is it different from using <Button as="a" ... syntax? In the future, I would suggest having proposals as RFC issues to avoid starting any implementation before we validate them as a team.

@matthieuh 

I agree with you. As you can read in this [RFC proposal](https://github.com/traefik/faency/issues/218), as the pattern is deprecated by Radix-UI, I knew it was very unlikely that we wouldn't follow it.

Next time, I'll wait for RFC review.

2021-12-17 13:49 UTC, paulocfjunior approved these changes

2022-04-01 14:16 UTC, closed without merging