chore: add license, Apache-2.0
traefik/faency pull request #369
Opened 2022-04-26 09:00 UTC by seedy

## Description

Adds license [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/)

Value in `package.json` follows [npm recommendations](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license), applying the SPDX OSI approved license ID, as visible [here](https://spdx.org/licenses/).

License was discussed and chosen with @ldez and @mmatur .

## Good PR checkboxes

- [ ] Change has been tested
- [ ] Added/Updated tests
- [ ] Added/Updated stories
- [x] PR follows [conventions](https://github.com/traefik/faency#how-to-contribute)
- [x] Labels are set
- [x] Project is linked

## Good Review checkboxes

<details>
<summary> ℹ️  Copy the snippet and paste in the review field to fill it</summary>

```markdown
- [ ] I've tested the changes
- [ ] I've agreed on the unit tests (soon to come)
- [ ] I've checked the stories
- [ ] I've read the code and understood it
- [ ] I don't have any more questions
- [ ] I've described any optional improvements
- [ ] I checked PR follows [conventions](https://github.com/traefik/faency#how-to-contribute)
```

</details>

2022-04-26 09:01 UTC, mmatur approved these changes

2022-04-26 10:37 UTC, ldez requested changes

2022-04-26 10:37 UTC, ldez commented on LICENSE
> +   Copyright [yyyy] [name of copyright owner]
```suggestion
   Copyright 2022 Traefik Labs
```

2022-04-26 10:38 UTC, ldez approved these changes

2022-04-26 10:39 UTC, ldez commented on README.md
> +See [LICENSE](./LICENSE) for more information.
```suggestion
```

2022-04-26 10:42 UTC, merged

2022-04-27 08:44 UTC, traefiker commented
:tada: This PR is included in version 6.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@traefiklabs/faency/v/6.1.0)
- [GitHub release](https://github.com/traefik/faency/releases/tag/v6.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: